# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 668999b97adfe04af30fe95829cae02185aae6c869eebaf4fdcec2f6df7c3f8b7f8bc7182c28c6dd3f8cb96558ce25eb778724ea9f489579d1da4fdb68ae1ee0

test:
  secret_key_base: 41c78a94cd5db2f8b47f7a472681481f7ce9e68293e92bdbc4ff49b16af1fafa8757939ec807eb36f1e317b10b6526db44f6ea703dadac674c6c8d9ad753a336

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
